baseurl = "https://technius.net/"
languageCode = "en-us"
title = "Bryan Tan's Blog"
theme = "plainsite"
description = "Random thoughts and ideas"
copyright = "Copyright (c) 2016-2019 Bryan Tan. Articles are licensed under CC-BY-4.0; code in articles licensed under MIT License."

# Using monokai theme: hugo gen chromastyles > static/css/highlight.css
# pygmentsStyle = "monokai"
pygmentsUseClasses = true
pygmentsCodefences = true

[params]
highlight = "monokai"
topmenu = "categories"

[menus]

[author]
name = "Bryan Tan"
github = "Technius"
