site_name: Bryan Tan's Website
remote_branch: source
site_url: https://technius.net
nav:
  - Home: index.md
  - Research: research.md
  - Projects: projects.md
#   - About: about.md
  - Blog: blog/index.md

theme:
  name: material
  palette:
    primary: deep purple
  features:
    - navigation.tabs
    - navigation.indexes

  # extra:
  # # Windmill theme
  #   article_nav_top: false
  #   article_nav_bottom: false
  #   history_buttons: false

plugins:
  - search
  - macros
  - blog:
      blog_toc: true
      post_excerpt: required
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
  - admonition
  - mdx_truly_sane_lists
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details

extra_javascript:
  - js/enhancements.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
