site_name: Bryan Tan's Website
remote_branch: site
nav:
  - Home: index.md
  - Projects: projects.md
#   - About: about.md
  - Research: research.md
  - Blog: blog/index.md

theme:
  name: material
  palette:
    primary: deep purple
  features:
    - navigation.tabs

  # extra:
  # # Windmill theme
  #   article_nav_top: false
  #   article_nav_bottom: false
  #   history_buttons: false

plugins:
  - search
  - macros
  - blogging:
      dirs:
        - blog

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
  - admonition
  - mdx_truly_sane_lists
